const express = require('express');
const Router = express.Router();
const suKienController = require('../controller/suKienController');
Router.get('/saptoi',suKienController.getSKSapToi);
Router.post('/timsukien',suKienController.timSuKien);
Router.put('/uploadminhchung/:id',suKienController.uploadMinhChung);
Router.get('/admin', suKienController.adminList);
Router.get('/all', suKienController.all);
Router.get('/', suKienController.index);
Router.post('/',suKienController.dangKySuKien);
Router.put('/update/:id', suKienController.updateEvent);
Router.get('/thamgia/:maSK', suKienController.participants);
Router.put('/thamgia/:maSK/:maTK', suKienController.updateParticipantStatus);
Router.delete('/thamgia/:maSK/:maTK', suKienController.cancelRegistration);
module.exports = Router;
